/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type = IDL.Variant({
  'flyer' : IDL.Null,
  'other' : IDL.Null,
  'demo' : IDL.Null,
  'journal' : IDL.Null,
  'notebook' : IDL.Null,
  'photo' : IDL.Null,
});
export const DownloadType = IDL.Variant({
  'art' : IDL.Null,
  'lyrics' : IDL.Null,
  'wallpaper' : IDL.Null,
  'demo' : IDL.Null,
  'zine' : IDL.Null,
  'poster' : IDL.Null,
});
export const ArchiveItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'type' : Type,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const CommunityPost = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Download = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'downloadType' : DownloadType,
  'description' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const MusicRelease = IDL.Record({
  'id' : IDL.Nat,
  'artworkDescription' : IDL.Text,
  'title' : IDL.Text,
  'trackList' : IDL.Vec(IDL.Text),
  'recordingNotes' : IDL.Text,
  'dateRecorded' : IDL.Text,
  'notes' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const Show = IDL.Record({
  'id' : IDL.Nat,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'date' : IDL.Text,
  'isUpcoming' : IDL.Bool,
  'notes' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCommunityPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArchiveItem' : IDL.Func(
      [IDL.Text, Type, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'createDownload' : IDL.Func(
      [IDL.Text, DownloadType, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createMusicRelease' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'createShow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'deleteArchiveItem' : IDL.Func([IDL.Nat], [], []),
  'deleteCommunityPost' : IDL.Func([IDL.Nat], [], []),
  'deleteDownload' : IDL.Func([IDL.Nat], [], []),
  'deleteMusicRelease' : IDL.Func([IDL.Nat], [], []),
  'deleteShow' : IDL.Func([IDL.Nat], [], []),
  'getArchiveItems' : IDL.Func([], [IDL.Vec(ArchiveItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getDownloads' : IDL.Func([], [IDL.Vec(Download)], ['query']),
  'getMusicReleases' : IDL.Func([], [IDL.Vec(MusicRelease)], ['query']),
  'getShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateArchiveItem' : IDL.Func(
      [IDL.Nat, IDL.Text, Type, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateDownload' : IDL.Func(
      [IDL.Nat, IDL.Text, DownloadType, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMusicRelease' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateShow' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type = IDL.Variant({
    'flyer' : IDL.Null,
    'other' : IDL.Null,
    'demo' : IDL.Null,
    'journal' : IDL.Null,
    'notebook' : IDL.Null,
    'photo' : IDL.Null,
  });
  const DownloadType = IDL.Variant({
    'art' : IDL.Null,
    'lyrics' : IDL.Null,
    'wallpaper' : IDL.Null,
    'demo' : IDL.Null,
    'zine' : IDL.Null,
    'poster' : IDL.Null,
  });
  const ArchiveItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'type' : Type,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const CommunityPost = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Download = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'downloadType' : DownloadType,
    'description' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const MusicRelease = IDL.Record({
    'id' : IDL.Nat,
    'artworkDescription' : IDL.Text,
    'title' : IDL.Text,
    'trackList' : IDL.Vec(IDL.Text),
    'recordingNotes' : IDL.Text,
    'dateRecorded' : IDL.Text,
    'notes' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const Show = IDL.Record({
    'id' : IDL.Nat,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'date' : IDL.Text,
    'isUpcoming' : IDL.Bool,
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCommunityPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArchiveItem' : IDL.Func(
        [IDL.Text, Type, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'createDownload' : IDL.Func(
        [IDL.Text, DownloadType, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createMusicRelease' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createShow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'deleteArchiveItem' : IDL.Func([IDL.Nat], [], []),
    'deleteCommunityPost' : IDL.Func([IDL.Nat], [], []),
    'deleteDownload' : IDL.Func([IDL.Nat], [], []),
    'deleteMusicRelease' : IDL.Func([IDL.Nat], [], []),
    'deleteShow' : IDL.Func([IDL.Nat], [], []),
    'getArchiveItems' : IDL.Func([], [IDL.Vec(ArchiveItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getDownloads' : IDL.Func([], [IDL.Vec(Download)], ['query']),
    'getMusicReleases' : IDL.Func([], [IDL.Vec(MusicRelease)], ['query']),
    'getShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateArchiveItem' : IDL.Func(
        [IDL.Nat, IDL.Text, Type, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateDownload' : IDL.Func(
        [IDL.Nat, IDL.Text, DownloadType, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMusicRelease' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateShow' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };