/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArchiveItem {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'tags' : Array<string>,
  'type' : Type,
  'description' : string,
}
export interface CommunityPost {
  'id' : bigint,
  'author' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Download {
  'id' : bigint,
  'title' : string,
  'downloadType' : DownloadType,
  'description' : string,
  'fileUrl' : string,
}
export type DownloadType = { 'art' : null } |
  { 'lyrics' : null } |
  { 'wallpaper' : null } |
  { 'demo' : null } |
  { 'zine' : null } |
  { 'poster' : null };
export interface MusicRelease {
  'id' : bigint,
  'artworkDescription' : string,
  'title' : string,
  'trackList' : Array<string>,
  'recordingNotes' : string,
  'dateRecorded' : string,
  'notes' : string,
  'subtitle' : string,
}
export interface Show {
  'id' : bigint,
  'venue' : string,
  'city' : string,
  'date' : string,
  'isUpcoming' : boolean,
  'notes' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export type Type = { 'flyer' : null } |
  { 'other' : null } |
  { 'demo' : null } |
  { 'journal' : null } |
  { 'notebook' : null } |
  { 'photo' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCommunityPost' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArchiveItem' : ActorMethod<
    [string, Type, string, string, Array<string>],
    undefined
  >,
  'createDownload' : ActorMethod<
    [string, DownloadType, string, string],
    undefined
  >,
  'createMusicRelease' : ActorMethod<
    [string, string, string, string, string, Array<string>, string],
    undefined
  >,
  'createShow' : ActorMethod<
    [string, string, string, boolean, string],
    undefined
  >,
  'deleteArchiveItem' : ActorMethod<[bigint], undefined>,
  'deleteCommunityPost' : ActorMethod<[bigint], undefined>,
  'deleteDownload' : ActorMethod<[bigint], undefined>,
  'deleteMusicRelease' : ActorMethod<[bigint], undefined>,
  'deleteShow' : ActorMethod<[bigint], undefined>,
  'getArchiveItems' : ActorMethod<[], Array<ArchiveItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getDownloads' : ActorMethod<[], Array<Download>>,
  'getMusicReleases' : ActorMethod<[], Array<MusicRelease>>,
  'getShows' : ActorMethod<[], Array<Show>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateArchiveItem' : ActorMethod<
    [bigint, string, Type, string, string, Array<string>],
    undefined
  >,
  'updateDownload' : ActorMethod<
    [bigint, string, DownloadType, string, string],
    undefined
  >,
  'updateMusicRelease' : ActorMethod<
    [bigint, string, string, string, string, string, Array<string>, string],
    undefined
  >,
  'updateShow' : ActorMethod<
    [bigint, string, string, string, boolean, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];